nodeLinker: node-modules

npmScopes:
  travellocal:
    npmAlwaysAuth: true
    npmAuthToken: "${GH_PACKAGES_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
